# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "develop"]

  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: ${{ vars.NODE_ENV }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Use variables
        run: |
          echo "VITE_APP_TITLE: $VITE_APP_TITLE"
          echo "VITE_API_URL: $VITE_API_URL"
          echo "VITE_BASE_URL: $VITE_BASE_URL"
          echo "NODE_ENV: $NODE_ENV"
          echo "SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}"
      - name: Prepare Environment Variables for Deployment
        id: prepare-env
        run: |
          # Convert repository or organization variables to JSON format
          echo '${{ toJSON(vars) }}' > env_vars.json
          # Convert JSON to .env format
          cat env_vars.json | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > .env
          #remove no longer needed env_vars.json file
          rm -f env_vars.json
          # Display the contents of the .env file (for debugging purposes)
          cat .env
      # Build and push the Docker image, passing the .env_file
      - name: Build and Push Container
        run: |-
          docker build \
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
      - name: Test and coverage
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build
        run: npm run build:$NODE_ENV
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
